# Cloudflare Pages 配置文件

# 构建命令
build.command = "npm run build"

# 构建输出目录
build.output = "dist"

# 构建环境变量
[build.environment]
NODE_VERSION = "18"

# 路由配置，确保SPA应用正常工作
[[routes]]
pattern = "/*"
script = ""
[[redirects]]
source = "/*"
destination = "/index.html"
status = 200 